// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkrVzpuT1mVgjfqfqMysq98Qj_X-RfBQg',
    appId: '1:323522395974:web:991ac3c43c29d78721ef47',
    messagingSenderId: '323522395974',
    projectId: 'first-app-nelson',
    authDomain: 'first-app-nelson.firebaseapp.com',
    databaseURL: 'https://first-app-nelson-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-nelson.firebasestorage.app',
    measurementId: 'G-ZXZJ59HDPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRABwJdHSVbPjxXMVgqow-1_6x8sjftGA',
    appId: '1:323522395974:android:ce5372d0d932ef3d21ef47',
    messagingSenderId: '323522395974',
    projectId: 'first-app-nelson',
    databaseURL: 'https://first-app-nelson-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-nelson.firebasestorage.app',
  );
}
